### ISSUE TITLE
A Small Request From A Legacy macOS User

### ISSUE THREAD

**Issue by DilettanteDev** [macmade/Hot#50] opened 2022-12-03 06:10 UTC
I'm using Hot on macOS 10.14.6 Mojave and see that v1.7.1 (110) is working for me now. 
Just for the record, I hadn't tried Hot since v1.6.1 where the speed/temperature graph wasn't working for me.

Now the request... Can we Intel users get some option to 'tick a box' so as to remove the Speed Limit? And just have the temperature and icon show? Maybe? Please?  ;-)
 
 
Using: Intel/Macmini//16GB/10.14.6 Mojave

**Comment by macmade** [comment] 2023-01-25 16:50
Closing as duplicate of #51

**Closed by macmade** 2023-01-25 16:50 UTC
