### ISSUE TITLE
No cumulative update, only incremental

### ISSUE THREAD

**Issue by antoniodini** [macmade/Hot#32] opened 2021-11-10 14:27 UTC
Hi,
I switch on my old MacBook Retina 12 Inch after few weeks and I have to do two update of Hot, one after another, to the last update 1.6.1 (90). 
I think this is incorrect, because minor releases should be cumulative and not incremental. 
Thank you

**Comment by macmade** [comment] 2021-11-10 14:30
Thanks for reporting this!  
This definitely sounds like a bug - I'll correct it asap.

**Comment by macmade** [comment] 2023-02-08 21:50
Cannot reproduce.  
Closing...

**Closed by macmade** 2023-02-08 21:50 UTC
Labels: bug
