### ISSUE TITLE
App Shutting Down on "View all Sensors..."

### ISSUE THREAD

**Issue by Devbearking** [macmade/Hot#85] opened 2024-06-06 07:58 UTC
The App is shutting down when "View all Sensors..." is opened and you try to scroll. 

https://github.com/macmade/Hot/assets/102469283/9a807c8b-b6ae-4c4f-9f33-07db812eaf12

**Comment by macmade** [comment] 2024-06-06 10:08
Duplicate of #81 - Closing.

**Closed by macmade** 2024-06-06 10:08 UTC
